.PHONY: clean All

All:
	@echo "----------Building project:[ Interface - Debug ]----------"
	@cd "Interface" && "$(MAKE)" -f  "Interface.mk"
clean:
	@echo "----------Cleaning project:[ Interface - Debug ]----------"
	@cd "Interface" && "$(MAKE)" -f  "Interface.mk" clean
